name: Build TrickyStore
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Original Repo
        uses: actions/checkout@v4
        with:
          repository: 5ec1cff/TrickyStore
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Check files (Debug)
        run: ls -la # Посмотрим, есть ли тут gradlew

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Remote Provider
        run: ./gradlew :remote-provider:assembleDebug

      - name: Build TrickyStore Module
        run: ./gradlew :module:assembleRelease

      - name: Upload Remote Provider APK
        uses: actions/upload-artifact@v4
        with:
          name: remote-provider-apk
          path: remote-provider/build/outputs/apk/debug/*.apk

      - name: Upload TrickyStore Module
        uses: actions/upload-artifact@v4
        with:
          name: TrickyStore-Module
          path: out/*.zip
